name: Deploy All Functions

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'

env:
  DOTNET_VERSION: '8.0.x'
  API_PROJECT_PATH: 'src/API/FiapX.API.csproj'
  WORKER_PROJECT_PATH: 'src/Worker/FiapX.Worker.csproj'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test src/FiapX.UnitTests/FiapX.UnitTests.csproj --configuration Release --no-build --verbosity normal

      - name: Publish API
        run: dotnet publish ${{ env.API_PROJECT_PATH }} -c Release -o publish-api

      - name: Publish Worker
        run: dotnet publish ${{ env.WORKER_PROJECT_PATH }} -c Release -o publish-worker

      - name: Zip API Artifact
        run: zip -r api.zip publish-api/*

      - name: Zip Worker Artifact
        run: |
          run: zip -r worker.zip publish-worker/*

      - name: Upload API Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-zip
          path: api.zip

      - name: Upload Worker Artifact
        uses: actions/upload-artifact@v4
        with:
          name: worker-zip
          path: worker.zip

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - app_name: func-fiapx-api
            artifact: api-zip
            package_file: api.zip
            secret_name: AZURE_FUNCTIONAPP_PUBLISH_PROFILE_API

          - app_name: func-fiapx-worker
            artifact: worker-zip
            package_file: worker.zip
            secret_name: AZURE_FUNCTIONAPP_PUBLISH_PROFILE_WORKER

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: .

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ matrix.app_name }}
          package: ./${{ matrix.package_file }}
          publish-profile: ${{ secrets[matrix.secret_name] }}